<?php
/**
 * @file
 * Contains field configuration scrambling methods.
 */

require_once 'includes/scrambler_field.entity.inc';
require_once 'includes/scrambler_field.view.inc';

/**
 * Implements hook_menu().
 */
function scrambler_field_menu() {
  $config = new \Drupal\scrambler_field\Controller\ConfigController();

  return $config->getMenuItems();
}

/**
 * Implements hook_permission().
 */
function scrambler_field_permission() {
  $permission = new \Drupal\scrambler_field\Security\Permission();

  return $permission->getPermission();
}

/**
 * Implements hook_scrambler_api().
 */
function scrambler_field_scrambler_api() {
  $params['scrambler_field'] = array(
    'shuffle_node_titles' => array(
      'base_table' => 'node_revision',
      'master_table' => 'node',
      'id' => 'vid',
      'fields' => array('title'),
      'method' => SCRAMBLER_METHOD_SHUFFLE_CHARACTERS,
    ),
  );

  return $params;
}
