<?php
/**
 * @file
 * A demo module that contains examples.
 *
 * Check the includes/scrambler.methods.inc file for more information about
 * the already available scrambling methods.
 */

/**
 * Implements hook_scrambler_api().
 */
function scrambler_example_scrambler_api() {
  // Define your module name.
  $params['scrambler_example'] = array(
    // Give a unique machine name for your scrambling group.
    'shuffle_words_for_title' => array(
      // Define base table where these fields are located.
      'base_table' => 'scrambler_example',
      // Define the id of the base table.
      'id' => 'sid',
      // Define field names.
      'fields' => array('title'),
      // Define a scramble method from the scrambler API.
      'method' => SCRAMBLER_METHOD_SHUFFLE_WORDS,
    ),
    // Give a unique machine name for your scrambling group.
    'custom_method_for_teaser' => array(
      // Define base table where these fields are located.
      'base_table' => 'scrambler_example',
      // Define the id of the base table.
      'id' => 'sid',
      // Define field names.
      'fields' => array('teaser'),
      // Define your custom scrambling method.
      'method' => 'custom_scrambling',
    ),
  );

  return $params;
}

/**
 * Implements hook_scrambler_methods().
 */
function scrambler_example_scrambler_methods() {
  return array('custom_scrambling' => 'Custom scrambling (scrambler_example module)');
}

/**
 * Custom scrambling method by the scrambler_example module.
 * @param type $data
 */
function _scrambler_example_method_custom_scrambling(&$data) {
  // Manipulate the $data parameter in which way you think is necessary.
  return str_replace('e', 'x', str_replace('a', 'y', $data));
}
