<?php
/**
 * @file
 *
 * Scrambler Example
 * A demo module that contains examples.
 */

/**
 * Implements hook_scrambler_api().
 */
function scrambler_example_scrambler_api() {
  // Define your module name.
  $params['scrambler_example'] = array(
    // Define a name to declare your custom group.
    'machine_name_group' => array(
      // Define base table where these fields are located.
      'base_table' => '',
      // Define field names.
      'fields' => array(''),
      // Define your scramble method. Ex: swap, scrape, delete, ...
      'method' => 'swap',
    ),
  );
  return $params;
}

function scrambler_example_scramble_method_mycustom() {

}
