<?php
/**
 * @file
 *   Contains scrambler user functions in order to scramble user data.
 */

/**
 * Implements hook_menu().
 */
function scrambler_user_menu() {
  return array(
    'admin/config/development/scrambler/user' => array(
      'title' => 'Configure Users Scrambler',
      'description' => 'Configure which user data need to be scrambled.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('scrambler_field_administer_users_form'),
      'weight' => -10,
      'type' => MENU_LOCAL_TASK,
      'access arguments' => array('administer scrambler users'),
      'file' => 'includes/scrambler_user.admin.inc',
      'file path' => drupal_get_path('module', 'scrambler_user'),
    ),
  );
}
